$pkg_cmd = <<-EOH
  wget -O puppetlabs-release-6-7.noarch.rpm http://yum.puppetlabs.com/el/6/products/i386/puppetlabs-release-6-7.noarch.rpm
  sudo rpm -ivh puppetlabs-release-6-7.noarch.rpm
  sudo yum install puppet -y
  sudo gem install rake builder serverspec --no-ri --no-rdoc
  ln -s /vagrant /home/vagrant/test
EOH

Vagrant.configure("2") do |conf|
  hostname = "ci-puppet"
  conf.vm.box      = "centos-6.4-x86_64"
  conf.vm.box_url  = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"
  conf.vm.hostname = hostname

  conf.vm.synced_folder "../manifests", "/etc/puppet/manifests", :owner => 'root', :group => 'root'
  conf.vm.synced_folder "../modules",   "/etc/puppet/modules",   :owner => 'root', :group => 'root'

  if Dir.glob("#{File.dirname(__FILE__)}/.vagrant/machines/#{hostname}/virtualbox/id").empty?
    conf.vm.provision :shell, :inline => $pkg_cmd
  end
end

